package com.demo.entities;
// Generated Jan 20, 2022, 8:39:05 PM by Hibernate Tools 5.1.10.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "role")
public class Role implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Integer roleId;

	@Column(name = "name", nullable = false, length = 250)
	private String name;

	@Column(name = "status", nullable = false)
	private boolean status;

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	private Set<User> users = new HashSet<User>(0);

	public Role() {
	}

	public Role(String name, boolean status) {
		this.name = name;
		this.status = status;
	}

	public Role(String name, boolean status, Set<User> users) {
		this.name = name;
		this.status = status;
		this.users = users;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof Role)) return false;
		return roleId != null && roleId.equals(((Role) o).getRoleId());
	}

	@Override
	public int hashCode() {
		return getClass().hashCode();
	}

}
